version: "3"
services:
  app:
    build: .
    ports:
      - "${MICROBLOG_PORT}:5000"
    depends_on:
      - "db"
    restart: unless-stopped

  db:
    image: mysql:8.0.21
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - "./db:/var/lib/mysql"

